pretrained_model_path: /content/AnimateDiff-SceneFusion/models/StableDiffusion/
motion_module: /content/AnimateDiff-SceneFusion/models/Motion_Module/mm_sd_v15.ckpt
output_dir: /content/AnimateDiff-SceneFusion/models/Motion_Module/test
train_data:
  csv_path:        "data/output.csv"
  video_folder:    "data/output"
  sample_size:     256
  sample_stride:   100
  sample_n_frames: 5
validation_data:
  prompts:
  - camera panning right to left, a bird's eye view of a row of buildings in a city with trees in the foreground, masterpiece, best quality
  video_length: 5
  width: 256
  height: 256
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-04
train_batch_size: 1
max_train_steps: 36
checkpointing_steps: 100
validation_steps: 1
trainable_modules:
- to_q
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true