image_finetune: false

output_dir: "outputs"
pretrained_model_path: "runwayml/stable-diffusion-v1-5"



train_data:
  video_path: "data/output/0.mp4"
  prompt: "a bird's - eye view of a row of buildings in a city with trees in the foreground"
  n_sample_frames: 6
  width: 256
  height: 256
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christmas tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 20
  width: 256
  height: 256
  guidance_scale: 12.5
  temporal_context": 24
  use_inv_latent": True
  num_inv_steps: 50

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

learning_rate:    3.e-5
train_batch_size: 1

max_train_epoch:      -1
max_train_steps:      1
checkpointing_epochs: -1
checkpointing_steps:  1000

validation_steps:       100
# validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: True
